#!/bin/bash
# replace german umlauts and predefined character sequences
# with html-entities in a file given as parameter
# place it into /usr/local/bin, make it executable
# to all and add it to nautilus-actions
# Michael Luthardt 2007
# http://dr-luthardt.de/

IN="$@"

cp $IN $IN.bak               # safety first
sed -i -e 's/\Ä/\&Auml;/g' \
    -i -e 's/\ä/\&auml;/g' \
    -i -e 's/\Ö/\&Ouml;/g' \
    -i -e 's/\ö/\&ouml;/g' \
    -i -e 's/\Ü/\&Uuml;/g' \
    -i -e 's/\ü/\&uuml;/g' \
    -i -e 's/\ß/\&szlig;/g' \
    -i -e 's/\^-/\&ndash;/g' \
    -i -e 's/\^ /\&nbsp;/g' \
    -i -e 's/\^</\&lt;/g' \
    -i -e 's/\^>/\&gt;/g' \
    -i -e 's/\^&/\&amp;/g' \
    -i -e 's/\^\^/\&#94;/g' \
    -i -e 's/\^x/\&times;/g' \
    -i -e 's/\^r/\&rarr;/g' \
    -i -e 's/\^b/\&bull;/g' \
    -i -e 's/\^e/\&#8644;/g' \
$IN
