#!/bin/bash
#
# Old resize.sh Script
#
#for file in *.JPG; do mv -i "${file}" "${file%%.JPG}.jpg"; done
#for f in *\ *; do mv "$f" "${f// /_}"; done
#for file in *.jpg
#do convert $file[1024X] ${file%.jpg}_web.jpg
#done




#!/bin/bash

# input file
IN="$@"

# output file
OUTPUT="JPG"

mkdir $OUTPUT
for i in $(find $IN -type f); do
	o=$OUTPUT/${i%.jpg}.jpg
	convert $i $o
done

zenity --info --text="Foto(s) verkleinert."
