#!/bin/bash
readarray FILENAME <<< "$(echo -e "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | sed -e 's/\r//g')"

# echo $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS > filename.txt

pdfunite $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS merged.pdf

zenity --info --text="PDF(s) zusammengeführt zu "merged.pdf""
