#!/bin/bash

mkdir original
kstelle=$(zenity --entry --text="Wie ist die Kostenstelle?")
readarray FILENAME <<< "$(echo -e "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | sed -e 's/\r//g')"

#echo -e "Logs: $(date)\n" > ~/Desktop/data.txt

for file in "${FILENAME[@]}"; do

    file=$(echo "$file" | tr -d $'\n')
    #echo "Current file: $file" >> ~/Desktop/data.txt
    cpdf \
        -add-text "Kostenstelle: $kstelle" \
        -topleft 30 \
        -font "Helvetica" \
        -font-size 20 \
        -color "red" \
        "$file" \
        -o "${file%.*}-gestempelt-"$kstelle".pdf"
		#convert "$file" -resize 1920x -quality 85% "${file%.*}-web.jpg"
    mv "$file" original/
    #ffmpeg -i "$file" -vn -acodec pcm_s16le -ac 2 -ar 48000 "${file%.*}.wav"
done

zenity --info --text="PDF gestempelt ("$kstelle")"
