#!/bin/bash

# input file
IN="$@"

# output file
OUTPUT="png"

mkdir $OUTPUT
for i in $(find $IN -type f); do
	o=$OUTPUT/${i%.psd}.png
	convert $i[0] $o
done

zenity --info --text="PSD(s) in PNG umgewandelt."
