#!/bin/bash

(
echo 25
echo "# Lese Dateien..."
sleep 1
# input file
IN="$@"
# output file
OUTPUT="web"

echo 50
echo "# Erstelle Ordner "web"..."
sleep 1
mkdir $OUTPUT

for i in $(find $IN -type f); do
	o=$OUTPUT/${i%.webm}-web.mp4
	echo 75
	echo "# Verkleinere $i ..."
	ffmpeg -i $i -movflags faststart -crf 26 $o
done

echo 100
echo "# Fertig!"

) | zenity --title "Videoskript" --progress --auto-kill
