#!/bin/bash

# old script
#OUT="web"
#mkdir $OUT
#for i in $(find $NAUTILUS_SCRIPT_SELECTED_FILE_PATHS -type f); do
#	o=${i%.jpg}-web.jpg
#	convert $i -resize 1920x -quality 85% $o
#	mv $o $OUT/
#done
#zenity --info --text="Foto(s) verkleinert."

mkdir hi-res
readarray FILENAME <<< "$(echo -e "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | sed -e 's/\r//g')"

#echo -e "Logs: $(date)\n" > ~/Desktop/data.txt

for file in "${FILENAME[@]}"; do

    file=$(echo "$file" | tr -d $'\n')
    #echo "Current file: $file" >> ~/Desktop/data.txt
		convert "$file" -resize 1920x -quality 85% "${file%.*}-web.jpg"
    mv "$file" hi-res/
    #ffmpeg -i "$file" -vn -acodec pcm_s16le -ac 2 -ar 48000 "${file%.*}.wav"
done

zenity --info --text="Bilder verkleinert (1920x)"
