#!/bin/bash

(
echo 25
echo "# Lese Dateien..."
sleep 1
# input file
IN="$@"

# output file
OUTPUT="subbed"

echo 50
echo "# Erstelle Ordner "subbed"..."
sleep 1
mkdir $OUTPUT

for i in $(find $IN -type f); do
	o=$OUTPUT/${i%.mp4}-subbed.mp4
	s=${i%.*}.srt
	echo 75
	echo "# Füge $s zu $i hinzu ..."
	ffmpeg -i $i -lavfi "subtitles=$s:force_style='BackColour=&H80000000,Fontname=Calibri,BorderStyle=4,Fontsize=20,Outline=0,Alignment=2,MarginV=40" -c:v libx264 -b:v 9M -minrate 5M -preset medium -c:a copy $o
	#"subtitles=$s:force_style='BackColour=&H80000000,Fontname=Calibri,BorderStyle=4,Fontsize=18,Outline=0,Alignment=2,MarginV=35" -c:v libx264 -b:v 9M -minrate 5M -preset slow -c:a copy $o
	# convert -interlace Plane -quality 85% Plane $i[1200x] $o

done

echo 100
echo "# Fertig!"

) | zenity --title "Videoskript" --progress --auto-kill
