#!/bin/bash
#
#OLD Script
# input file
#IN="$@"
# output folder
#mkdir mp3
#for i in $(find $IN -type f -name "*.flac"); do
	#ffmpeg -i "$i" -ab 264k -map_metadata 0 -id3v2_version 3 "mp3/$(basename "${i/.flac}")-264k.mp3"
	#f="${a/%flac/mp3}"
  #ffmpeg -nostdin -i "$i" -ab 264k -map_metadata 0 -id3v2_version 3 "mp3/$f"
#done
#!/bin/bash

{
mkdir orig
readarray FILENAME <<< "$(echo -e "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | sed -e 's/\r//g')"

#echo -e "Logs: $(date)\n" > ~/Desktop/data.txt

for file in "${FILENAME[@]}"; do

    file=$(echo "$file" | tr -d $'\n')
    #echo "Current file: $file" >> ~/Desktop/data.txt
		ffmpeg -i "$file" -ab 264k -map_metadata 0 -id3v2_version 3 "${file%.*}-264k.mp3"
    mv "$file" orig/
    #ffmpeg -i "$file" -vn -acodec pcm_s16le -ac 2 -ar 48000 "${file%.*}.wav"
done

zenity --info --text="In MP3 (264k) konvertiert."
} 2>~ffmpeg.log
